# Generated by Django 4.2.1 on 2023-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XYZ_sales_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('order_date', models.DateField(max_length=50)),
                ('ship_date', models.DateField(max_length=50)),
                ('ship_mode', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('segment', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('sales', models.IntegerField(max_length=200)),
            ],
        ),
    ]
